### PR TITLE
Export fitness as a `JSON` file

### PR DESCRIPTION
**Pull request by WillHannon-MCB**
This pull request introduces a new rule to the pipeline that enables the storage of amino acid fitness estimates in a `JSON` file. It also includes both metadata and summary statistics for fitness at each site. The intent behind this addition is to provide a data format that seamlessly integrates with the Chodera lab's interactive protein visualization tool.

The stored amino acid fitness includes a filter to exclude any mutations where the minimum expected count falls below the specified [minimum expected count as defined in the config file](https://github.com/jbloomlab/SARS2-mut-fitness/blob/b1717d089e4ccf36bed833af07162fc534ef4cb6/config.yaml#L130). Also, stop codons are omitted from the calculations of summary statistics at each site.

### CODE REVIEW

**Review by jbloom — COMMENTED** [review]
@WillHannon-MCB, this looks great to me. Just one question: do we want to track the JSON files themselves in the repo (eg, with `git-lfs`)? How large are they both as full files and gzipped? If they aren't huge, maybe we want to track them in repo too so others can just get JSONs without running repo?

**Comment by WillHannon-MCB** [comment]
@jbloom, the un-compressed file is ~25M, so pretty big. The compressed file is ~1.4M.

**Comment by jbloom** [comment]
That's not too huge. Can you write file as compressed and then track those? I think this is best approach, and let me know when that is done and I will approve request.

**Comment by WillHannon-MCB** [comment]
Alright, I've gzipped the files and added them to `git lfs`.

**Pull request merged**
